markdown: kramdown
#baseurl:  /portfolio
exclude: ['README.md']


sass:
      sass_dir: _sass
      style: compressed

collections:
      proyectos:
        output: true


plugins:
- jekyll-autoprefixer
