markdown: kramdown
#baseurl:  /portfolio
exclude: ['README.md']

url: http://harbyrobayo.com

sass:
      sass_dir: _sass
      style: compressed

collections:
      proyectos:
        output: true


plugins:
- jekyll-autoprefixer
theme: jekyll-theme-cayman